"""
100 Demo-Fragen fuer den Bayer Credit Analyst Agent.
Jede Frage hat eine eindeutige ID, Task-Typ, Label, Fragetext und Keywords.
Die fn-Felder werden in run_demo_100.py mit den Simulation-Engine-Funktionen verknuepft.
"""

RAW_QUESTIONS = [
    # ── T1 KREDITBLOCK (1–20) ───────────────────────────────────────────────
    {"id":  1, "task":"T1", "label":"Kreditblock BP 2000002",
     "q":"Warum ist Business Partner 2000002 gesperrt?",
     "kw":["2000002","gesperrt","kreditblock","sperr","blocked"]},
    {"id":  2, "task":"T1", "label":"Welche Auftraege sind betroffen",
     "q":"Welche Auftraege sind wegen Kreditblock fuer BP 2000002 gesperrt?",
     "kw":["auftraege","gesperrt","2000002","sales document","blocked order"]},
    {"id":  3, "task":"T1", "label":"Blockierungsursache Code 01",
     "q":"Was bedeutet Block-Code 01 im Kreditmanagement?",
     "kw":["block-code","code 01","blockierungsursache","block code"]},
    {"id":  4, "task":"T1", "label":"Kreditlimit ueberschritten",
     "q":"Das Kreditlimit von BP 2000002 ist ueberschritten - erklaere die Situation.",
     "kw":["kreditlimit ueberschritten","limit ueberschritten","exceed","ueberschritt"]},
    {"id":  5, "task":"T1", "label":"Gesamtwert gesperrter Auftraege",
     "q":"Wie hoch ist der Gesamtwert der gesperrten Auftraege fuer Agro Solutions?",
     "kw":["gesamtwert","agro solutions","gesperrte auftraege","total blocked"]},
    {"id":  6, "task":"T1", "label":"Resubmission-Datum",
     "q":"Wann ist das naechste Wiedervorlage-Datum fuer BP 2000002?",
     "kw":["wiedervorlage","resubmission","naechste pruefdatum","2000002 datum"]},
    {"id":  7, "task":"T1", "label":"Kritischer Kunde",
     "q":"Ist BP 2000002 als kritischer Kunde markiert?",
     "kw":["kritischer kunde","businesspartneriscritical","critical customer"]},
    {"id":  8, "task":"T1", "label":"Kreditauslastung BP 2000002",
     "q":"Wie hoch ist die Kreditauslastung von BP 2000002 in Prozent?",
     "kw":["kreditauslastung 2000002","auslastung 2000002","2000002 prozent"]},
    {"id":  9, "task":"T1", "label":"Vergleich BP 1000001 vs 2000002",
     "q":"Vergleiche den Kreditstatus von BP 1000001 und BP 2000002.",
     "kw":["vergleich","1000001 vs 2000002","vergleiche bp","compare bp"]},
    {"id": 10, "task":"T1", "label":"Massnahmen bei Kreditblock",
     "q":"Welche konkreten Massnahmen empfiehlt der Agent um den Kreditblock fuer 2000002 aufzuheben?",
     "kw":["massnahmen aufheben","kreditblock aufheben","empfehlung block","freigabe block"]},
    {"id": 11, "task":"T1", "label":"Eskalation bei Block",
     "q":"An wen muss der Kreditblock von BP 2000002 eskaliert werden?",
     "kw":["eskalation block","eskaliert","an wen block","zustaendig block"]},
    {"id": 12, "task":"T1", "label":"Negative Events BP 2000002",
     "q":"Gibt es negative Ereignisse im Kreditprofil von BP 2000002?",
     "kw":["negative ereignisse","negative events","2000002 ereignisse"]},
    {"id": 13, "task":"T1", "label":"Kreditblock Zusammenfassung",
     "q":"Fasse den Kreditstatus von Business Partner 2000002 kurz zusammen.",
     "kw":["zusammenfassung 2000002","kurze zusammenfassung","summary 2000002","status zusammen"]},
    {"id": 14, "task":"T1", "label":"Kreditlimit Gueltigkeit",
     "q":"Wann laeuft das genehmigte Kreditlimit von BP 2000002 ab?",
     "kw":["kreditlimit ablauf","validity","gueltigkeit limit","2000002 gueltig"]},
    {"id": 15, "task":"T1", "label":"Risikoklasse BP 2000002",
     "q":"Welche Risikoklasse hat BP 2000002 und was bedeutet das?",
     "kw":["risikoklasse 2000002","04 bedeutet","risk class 2000002"]},
    {"id": 16, "task":"T1", "label":"Bonitaetsscore BP 2000002",
     "q":"Wie ist der Bonitaetsscore von BP 2000002 zu bewerten?",
     "kw":["bonitaetsscore 2000002","score 180","180 score","score 2000002"]},
    {"id": 17, "task":"T1", "label":"Sales Dokument 0000012345",
     "q":"Zeige Details zum gesperrten Verkaufsauftrag 0000012345.",
     "kw":["0000012345","sales document","verkaufsauftrag detail","auftrag detail"]},
    {"id": 18, "task":"T1", "label":"Kreditblock Release",
     "q":"Was muss passieren damit Auftrag 0000012345 freigegeben wird?",
     "kw":["freigabe auftrag","release auftrag","auftrag freigeben","0000012345 freigabe"]},
    {"id": 19, "task":"T1", "label":"Kreditblock Ursache Analyse",
     "q":"Analysiere alle Ursachen des Kreditblocks bei Agro Solutions detailliert.",
     "kw":["ursachen kreditblock","agro solutions block","kreditblock analyse","detaillierte analyse block"]},
    {"id": 20, "task":"T1", "label":"Praevention Kreditblock",
     "q":"Wie haette der Kreditblock bei BP 2000002 verhindert werden koennen?",
     "kw":["praevention","verhindert","vorbeugung block","verhindern block"]},

    # ── T2 TRM UTILIZATION (21–40) ──────────────────────────────────────────
    {"id": 21, "task":"T2", "label":"TRM Auslastung BP 1000001",
     "q":"Wie hoch ist die Kreditlimit-Auslastung von BP 1000001?",
     "kw":["auslastung 1000001","kreditlimit-auslastung","trm 1000001","limit 1000001"]},
    {"id": 22, "task":"T2", "label":"Sicherheiten BP 1000001",
     "q":"Welche Treasury-Sicherheiten hat BP 1000001 hinterlegt?",
     "kw":["sicherheiten 1000001","treasury","collateral","bankgarantie"]},
    {"id": 23, "task":"T2", "label":"TRM Ampelstatus BP 1000001",
     "q":"Welche Farbe hat die TRM-Ampel fuer Business Partner 1000001?",
     "kw":["ampel 1000001","ampelstatus","trm ampel","gruene ampel"]},
    {"id": 24, "task":"T2", "label":"Genehmigtes vs berechnetes Limit",
     "q":"Was ist der Unterschied zwischen genehmigtem Limit und berechnetem Limit bei BP 1000001?",
     "kw":["genehmigtes limit","berechnetes limit","unterschied limit","calculated limit"]},
    {"id": 25, "task":"T2", "label":"Beantragtes Kreditlimit",
     "q":"Wie hoch ist das beantragte Kreditlimit von BP 1000001?",
     "kw":["beantragt","requested limit","kreditlimit beantrag","270000"]},
    {"id": 26, "task":"T2", "label":"TRM Auslastung BP 2000002",
     "q":"Zeige die TRM-Auslastungsbewertung fuer BP 2000002 mit Risikoampel.",
     "kw":["trm 2000002","auslastung 2000002","risikoampel 2000002","trm-bewertung"]},
    {"id": 27, "task":"T2", "label":"Limit in Waehrung",
     "q":"In welcher Waehrung ist das Kreditlimit von BP 1000001 festgelegt?",
     "kw":["waehrung","currency","eur limit","limit waehrung"]},
    {"id": 28, "task":"T2", "label":"TRM Schwellenwerte",
     "q":"Ab welcher Auslastung wechselt die TRM-Ampel von Gruen auf Amber?",
     "kw":["schwellenwert","schwelle","70 prozent","amber schwelle","gruen amber"]},
    {"id": 29, "task":"T2", "label":"Limitaenderung Empfehlung",
     "q":"Sollte das Kreditlimit fuer BP 1000001 erhoet werden?",
     "kw":["limiterhohung","limit erhoehen","erhoehung empfehlung","limit empfehlung"]},
    {"id": 30, "task":"T2", "label":"Sicherheitendeckung",
     "q":"Zu wie viel Prozent decken die Sicherheiten das Kreditlimit von BP 1000001 ab?",
     "kw":["sicherheitendeckung","deckung sicherheiten","collateral coverage","prozent sicherheit"]},
    {"id": 31, "task":"T2", "label":"Kreditlimit Letzte Aenderung",
     "q":"Wann wurde das Kreditlimit von BP 1000001 zuletzt geaendert?",
     "kw":["letzte aenderung","lastchangedate","aenderung datum","zuletzt geaendert"]},
    {"id": 32, "task":"T2", "label":"Kreditlimit Gueltigkeit BP 1000001",
     "q":"Bis wann gilt das genehmigte Kreditlimit von BP 1000001?",
     "kw":["gueltigkeit 1000001","validity end","kreditlimit bis","limit gueltig bis"]},
    {"id": 33, "task":"T2", "label":"TRM Monitoring Empfehlung",
     "q":"Welche Monitoring-Massnahmen empfiehlt der Agent fuer BP 1000001?",
     "kw":["monitoring 1000001","monitoring massnahmen","ueberwachung 1000001","monitor empfehlung"]},
    {"id": 34, "task":"T2", "label":"Vergleich Ampelstatus",
     "q":"Vergleiche den TRM-Ampelstatus von BP 1000001 und BP 2000002.",
     "kw":["vergleich ampel","ampel vergleich","1000001 vs 2000002 trm","compare trm"]},
    {"id": 35, "task":"T2", "label":"TRM Limitanpassung BP 2000002",
     "q":"Was empfiehlt der Agent fuer das Kreditlimit von BP 2000002 nach Auslastungsanalyse?",
     "kw":["limitanpassung 2000002","limit 2000002 empfehlung","anpassung 2000002","2000002 limit action"]},
    {"id": 36, "task":"T2", "label":"Bankgarantie Details",
     "q":"Von welcher Bank wurde die Garantie fuer BP 1000001 ausgestellt?",
     "kw":["deutsche bank","bank guarantee","bankgarantie detail","ausgestellt garantie"]},
    {"id": 37, "task":"T2", "label":"Bankgarantie Wert",
     "q":"Wie hoch ist der Wert der hinterlegten Bankgarantie von BP 1000001?",
     "kw":["wert garantie","25000","bankgarantie wert","guarantee value"]},
    {"id": 38, "task":"T2", "label":"TRM Eskalation Schwelle",
     "q":"Wann muss eine TRM-Ueberschreitung eskaliert werden?",
     "kw":["trm eskalation schwelle","90 prozent eskalation","eskalation schwelle trm","trm tier"]},
    {"id": 39, "task":"T2", "label":"Kreditkontrolle Segment",
     "q":"In welchem Kreditsegment ist BP 1000001 eingeteilt?",
     "kw":["kreditsegment","segment 0001","credit segment","segmentzuordnung"]},
    {"id": 40, "task":"T2", "label":"TRM vollstaendige Analyse",
     "q":"Erstelle eine vollstaendige TRM-Auslastungsanalyse fuer Business Partner 1000001.",
     "kw":["vollstaendige trm","vollstaendige analyse trm","complete trm","trm vollanalyse"]},

    # ── T3 DCD DECISION SUPPORT (41–60) ────────────────────────────────────
    {"id": 41, "task":"T3", "label":"Akkreditiv genehmigt",
     "q":"Kunde 1000001 moechte ein Akkreditiv (Letter of Credit) hinterlegen - ist das zulaessig?",
     "kw":["akkreditiv","letter of credit","irrevocable lc","zulaessig lc","lc hinterlegen"]},
    {"id": 42, "task":"T3", "label":"Personal Cheque abgelehnt",
     "q":"Ein Kunde schlaegt einen Personal Cheque als DCD-Instrument vor - ist das zulaessig?",
     "kw":["personal cheque","cheque","scheck","personal check"]},
    {"id": 43, "task":"T3", "label":"Bankgarantie als DCD",
     "q":"Kann eine Bankgarantie als DCD-Sicherheit fuer BP 1000001 eingesetzt werden?",
     "kw":["bankgarantie dcd","bank guarantee dcd","garantie dcd","dcd bankgarantie"]},
    {"id": 44, "task":"T3", "label":"Standby LC",
     "q":"Ist ein Standby Letter of Credit als DCD-Instrument bei Bayer zugelassen?",
     "kw":["standby lc","standby letter","standby akkreditiv","standby zugelassen"]},
    {"id": 45, "task":"T3", "label":"Documentary Collection",
     "q":"Kann ein Dokumenten-Inkasso (Documentary Collection) als Sicherheit verwendet werden?",
     "kw":["documentary collection","inkasso","dokumenten inkasso","d/a","d/p"]},
    {"id": 46, "task":"T3", "label":"Vorauszahlung als DCD",
     "q":"Ist Vorauszahlung als DCD-Instrument bei Bayer akzeptiert?",
     "kw":["vorauszahlung dcd","advance payment dcd","prepayment dcd","vorauszahlung instrument"]},
    {"id": 47, "task":"T3", "label":"D&B Rating BP 1000001",
     "q":"Welches D&B-Rating hat BP 1000001 und wie beeinflusst das die DCD-Entscheidung?",
     "kw":["d&b rating","dandb rating","bb+ rating","dun bradstreet","d&b 1000001"]},
    {"id": 48, "task":"T3", "label":"Insolvenzpruefung",
     "q":"Ist BP 1000001 insolvent oder gibt es laufende Gerichtsverfahren?",
     "kw":["insolvenz","insolvent","bankrupt","gerichtsverfahren","legal proceeding"]},
    {"id": 49, "task":"T3", "label":"DCD Risikoklasse Anforderung",
     "q":"Welche DCD-Anforderungen gelten fuer Kunden der Risikoklasse 03?",
     "kw":["risikoklasse 03","dcd anforderung","klasse 03 dcd","risk class 03 dcd"]},
    {"id": 50, "task":"T3", "label":"Bestaetigtes Akkreditiv",
     "q":"Ist ein bestaedigtes Akkreditiv (Confirmed Letter of Credit) auf der Bayer-Positivliste?",
     "kw":["bestaetigt akkreditiv","confirmed lc","confirmed letter","bestaedigtes lc"]},
    {"id": 51, "task":"T3", "label":"DCD Genehmigungsstufe",
     "q":"Wer muss ein DCD-Instrument bei Risikoklasse 02 genehmigen?",
     "kw":["genehmigungsstufe dcd","dcd genehmigung","wer genehmigt dcd","dcd tier 2"]},
    {"id": 52, "task":"T3", "label":"Bestehende Sicherheiten",
     "q":"Welche Sicherheiten hat Kunde 1000001 bereits hinterlegt?",
     "kw":["bestehende sicherheiten","bereits hinterlegt","vorhandene sicherheiten","existing collateral"]},
    {"id": 53, "task":"T3", "label":"DCD Vollpruefung BP 1000001",
     "q":"Fuehre eine vollstaendige DCD-Pruefung fuer Business Partner 1000001 durch.",
     "kw":["vollstaendige dcd pruefung","dcd vollpruefung","complete dcd check","dcd analyse 1000001"]},
    {"id": 54, "task":"T3", "label":"Nicht zugelassene Instrumente",
     "q":"Welche Sicherheitsinstrumente sind bei Bayer nicht zugelassen?",
     "kw":["nicht zugelassen","verboten instrument","abgelehnte instrumente","not approved"]},
    {"id": 55, "task":"T3", "label":"DCD fuer kritischen Kunden",
     "q":"Welches DCD-Instrument eignet sich am besten fuer einen kritischen Kunden (Risikoklasse 04)?",
     "kw":["dcd risikoklasse 04","dcd kritischer kunde","instrument risikoklasse 04","best instrument"]},
    {"id": 56, "task":"T3", "label":"Kreditwuerdigkeitskommentar",
     "q":"Was sagt der D&B-Kommentar ueber die Zahlungshistorie von BP 1000001?",
     "kw":["kreditwuerdigkeitskommentar","d&b kommentar","standing comment","zahlungshistorie d&b"]},
    {"id": 57, "task":"T3", "label":"DCD Laufzeit Pruefung",
     "q":"Ist die Laufzeit der hinterlegten Bankgarantie fuer BP 1000001 noch gueltig?",
     "kw":["laufzeit garantie","validity garantie","gueltigkeit garantie","validity collateral"]},
    {"id": 58, "task":"T3", "label":"DCD Tier 3 Trigger",
     "q":"Unter welchen Umstaenden eskaliert eine DCD-Entscheidung zum Credit Committee (Tier 3)?",
     "kw":["dcd tier 3","credit committee dcd","eskalation tier 3","dcd ausnahme"]},
    {"id": 59, "task":"T3", "label":"Wechsel DCD-Instrument",
     "q":"Kunde 1000001 moechte die Bankgarantie durch ein Akkreditiv ersetzen - ist das moeglich?",
     "kw":["wechsel instrument","ersetzen garantie","bankgarantie ersetzen","instrument wechsel"]},
    {"id": 60, "task":"T3", "label":"DCD Gesamtuebersicht",
     "q":"Gib eine Gesamtuebersicht aller genehmigten DCD-Instrumente gemaess Bayer-Richtlinie.",
     "kw":["gesamtuebersicht dcd","alle instrumente","positivliste vollstaendig","approved instruments list"]},

    # ── T4 PAYMENT TERMS (61–75) ────────────────────────────────────────────
    {"id": 61, "task":"T4", "label":"Zahlungsbedingung CU10000001 konform",
     "q":"Welche Zahlungsbedingungen hat Kunde CU10000001 und sind diese policy-konform?",
     "kw":["zahlungsbedingungen cu10000001","cu10000001 konform","payment term cu10000001","zb30"]},
    {"id": 62, "task":"T4", "label":"60 Tage Risikoklasse 04 Mismatch",
     "q":"Kunde mit Risikoklasse 04 beantragt 60 Tage Zahlungsziel - ist das zulaessig?",
     "kw":["60 tage","risikoklasse 04 zahlung","60 days risk class","policy-konform 60"]},
    {"id": 63, "task":"T4", "label":"ZB30 Code erklaert",
     "q":"Was bedeutet der Zahlungsbedingungscode ZB30?",
     "kw":["zb30","zahlungscode","payment term code","zb30 bedeutet"]},
    {"id": 64, "task":"T4", "label":"Maximale Zahlungsziele",
     "q":"Welche maximalen Zahlungsziele sind fuer jede Risikoklasse erlaubt?",
     "kw":["maximale zahlungsziele","max days","zahlungsziel matrix","risikoklasse zahlungsziel"]},
    {"id": 65, "task":"T4", "label":"Vorauszahlung Pflicht",
     "q":"Fuer welche Risikoklasse ist Vorauszahlung obligatorisch?",
     "kw":["vorauszahlung pflicht","advance payment only","obligatorisch","risikoklasse 04 vorauszahlung"]},
    {"id": 66, "task":"T4", "label":"Risikoklasse 01 Limit",
     "q":"Bis zu wie vielen Tagen Zahlungsziel ist Risikoklasse 01 berechtigt?",
     "kw":["risikoklasse 01 limit","klasse 01 zahlungsziel","90 tage risikoklasse 01","net 90"]},
    {"id": 67, "task":"T4", "label":"Risikoklasse 02 Limit",
     "q":"Welches maximale Zahlungsziel gilt fuer Kunden mit Risikoklasse 02?",
     "kw":["risikoklasse 02 zahlungsziel","klasse 02 limit","45 tage","net 45"]},
    {"id": 68, "task":"T4", "label":"Risikoklasse 03 Limit",
     "q":"Was ist das maximale Zahlungsziel fuer Risikoklasse 03?",
     "kw":["risikoklasse 03 zahlungsziel","30 tage risikoklasse 03","net 30","klasse 03 zahlung"]},
    {"id": 69, "task":"T4", "label":"Borderline Zahlungsbedingung",
     "q":"Was passiert wenn das Zahlungsziel an der Grenze der Policy-Toleranz liegt?",
     "kw":["borderline","grenze toleranz","zahlungsziel grenze","borderline payment"]},
    {"id": 70, "task":"T4", "label":"Abstimmungskonto CU10000001",
     "q":"Welches Abstimmungskonto ist fuer Kunde CU10000001 hinterlegt?",
     "kw":["abstimmungskonto","reconciliation account","140000","buchungskonto"]},
    {"id": 71, "task":"T4", "label":"Zahlungsmethode CU10000001",
     "q":"Welche Zahlungsmethode ist fuer Kunde CU10000001 festgelegt?",
     "kw":["zahlungsmethode","payment method","zahlungsart","payment method list"]},
    {"id": 72, "task":"T4", "label":"Zahlungssperre Pruefung",
     "q":"Hat Kunde CU10000001 eine Zahlungssperre?",
     "kw":["zahlungssperre","payment block","zahlungsblockierung","blocking reason"]},
    {"id": 73, "task":"T4", "label":"Neue Zahlungsbedingung beantragen",
     "q":"Kunde CU10000001 moechte Zahlungsziel von 30 auf 45 Tage erhoehen - wie ist das zu bewerten?",
     "kw":["erhoehung zahlungsziel","30 auf 45","payment term increase","zahlungsziel erhoehung"]},
    {"id": 74, "task":"T4", "label":"Zahlungsbedingung Genehmigung",
     "q":"Wer muss eine Zahlungsbedingungsaenderung bei Risikoklasse 02 genehmigen?",
     "kw":["zahlungsbedingung genehmigung","wer genehmigt zahlung","payment approval","payment change approval"]},
    {"id": 75, "task":"T4", "label":"Vollstaendige Payment Term Analyse",
     "q":"Erstelle eine vollstaendige Analyse der Zahlungsbedingungen fuer CU10000001.",
     "kw":["vollstaendige payment analyse","complete payment analysis","zahlungsanalyse vollstaendig","payment full analysis"]},

    # ── T5 SEASONAL FINANCING (76–90) ───────────────────────────────────────
    {"id": 76, "task":"T5", "label":"Saisonfinanzierung BP 1000001 geeignet",
     "q":"Ist BP 1000001 fuer das saisonale Fruehjahrs-Finanzierungsprogramm 2025 geeignet?",
     "kw":["saisonale finanzierung 1000001","fruehjahr 2025","eligible 1000001","fruehjahrsprogramm"]},
    {"id": 77, "task":"T5", "label":"Saisonfinanzierung BP 2000002 nicht geeignet",
     "q":"Kann BP 2000002 (gesperrt, Risikoklasse 04) saisonale Finanzierung beantragen?",
     "kw":["saisonale finanzierung 2000002","2000002 saisonal","not eligible 2000002","saisonal gesperrt"]},
    {"id": 78, "task":"T5", "label":"Eligibility Score Erklaerung",
     "q":"Wie wird der Eligibility-Score fuer saisonale Finanzierung berechnet?",
     "kw":["eligibility score","score berechnung","scoring saisonal","wie berechnet eligibility"]},
    {"id": 79, "task":"T5", "label":"D&B Datenalter Guardrail G5",
     "q":"Wie alt duerfen D&B-Daten maximal sein damit Guardrail G5 nicht ausgeloest wird?",
     "kw":["guardrail g5","d&b alter","90 tage d&b","datenalter g5"]},
    {"id": 80, "task":"T5", "label":"Scorebeitraege Risikoklasse",
     "q":"Wie viele Punkte traegt Risikoklasse 01 zum Eligibility-Score bei?",
     "kw":["scorebeitrag risikoklasse","punkte risikoklasse","40 punkte","score risikoklasse 01"]},
    {"id": 81, "task":"T5", "label":"D&B Rating Einfluss",
     "q":"Wie beeinflusst ein D&B Rating von CCC den Eligibility-Score?",
     "kw":["ccc rating","d&b ccc","dandb ccc rating","ccc einfluss score"]},
    {"id": 82, "task":"T5", "label":"Kreditblock Einfluss auf Eligibility",
     "q":"Um wie viele Punkte wird der Eligibility-Score bei einem aktiven Kreditblock reduziert?",
     "kw":["kreditblock score","block punkte","block einfluss","30 punkte block"]},
    {"id": 83, "task":"T5", "label":"Negative Events Einfluss",
     "q":"Wie beeinflussen negative Ereignisse den Eligibility-Score?",
     "kw":["negative events score","ereignisse score","einfluss negative","neg events punkte"]},
    {"id": 84, "task":"T5", "label":"Conditional Entscheidung",
     "q":"Was bedeutet eine Conditional-Entscheidung bei der saisonalen Finanzierungspruefung?",
     "kw":["conditional","bedingt geeignet","conditional entscheidung","conditional eligibility"]},
    {"id": 85, "task":"T5", "label":"D&B Datum BP 2000002",
     "q":"Ist das D&B-Datum von BP 2000002 aktuell oder veraltet?",
     "kw":["d&b datum 2000002","d&b veraltet","dandb alt 2000002","stale d&b"]},
    {"id": 86, "task":"T5", "label":"Fruehjahr vs Herbst Programm",
     "q":"Gibt es einen Unterschied zwischen dem Fruehjahrs- und Herbst-Finanzierungsprogramm?",
     "kw":["fruehjahr vs herbst","herbst programm","saisonprogramm unterschied","spring fall program"]},
    {"id": 87, "task":"T5", "label":"Mindest Score Eligibility",
     "q":"Welcher Mindest-Score ist fuer die Freigabe der saisonalen Finanzierung erforderlich?",
     "kw":["mindest score","mindest eligibility","70 punkte","minimum score eligible"]},
    {"id": 88, "task":"T5", "label":"Saisonal Tier 1 Freigabe",
     "q":"Wann kann Tier 1 die saisonale Finanzierung selbst freigeben?",
     "kw":["tier 1 freigabe","analyst freigabe","tier 1 saisonal","eligible tier 1"]},
    {"id": 89, "task":"T5", "label":"Saisonal Tier 3 Eskalation",
     "q":"Wann wird die saisonale Finanzierung zum Credit Committee eskaliert?",
     "kw":["tier 3 saisonal","credit committee saisonal","not eligible eskalation","tier 3 seasonal"]},
    {"id": 90, "task":"T5", "label":"Saisonal Vollanalyse BP 1000001",
     "q":"Erstelle eine vollstaendige Saisonfinanzierungs-Analyse fuer BP 1000001.",
     "kw":["vollstaendige saisonal","complete seasonal","saisonal vollanalyse","full seasonal 1000001"]},

    # ── ESKALATION / GUARDRAILS (91–100) ────────────────────────────────────
    {"id": 91, "task":"ESK", "label":"Dreistufiges Eskalationsmodell",
     "q":"Erklaere das dreistufige Eskalationsmodell des Bayer Credit Analyst Agenten.",
     "kw":["dreistufig","eskalationsmodell","tier 1 tier 2 tier 3","three tier model"]},
    {"id": 92, "task":"ESK", "label":"Guardrail G1 Read-Only",
     "q":"Was besagt Guardrail G1 und warum ist Read-Only wichtig?",
     "kw":["guardrail g1","read-only","g1 read only","kein schreibzugriff"]},
    {"id": 93, "task":"ESK", "label":"Guardrail G3 DCD",
     "q":"Was prueft Guardrail G3 und wie schuetzt es vor falschen Instrumenten?",
     "kw":["guardrail g3","g3 dcd","g3 instrument","g3 positivliste"]},
    {"id": 94, "task":"ESK", "label":"Guardrail G5 Datenalter",
     "q":"Welche Regel gilt fuer das Datenalter bei D&B-Bonitaetsdaten (Guardrail G5)?",
     "kw":["guardrail g5 datenalter","g5 regel","d&b 90 tage g5","datenalter guardrail"]},
    {"id": 95, "task":"ESK", "label":"Guardrail G6 Konfidenz",
     "q":"Wann loest Guardrail G6 eine automatische Eskalation aus?",
     "kw":["guardrail g6","konfidenz","g6 70 prozent","g6 eskalation"]},
    {"id": 96, "task":"ESK", "label":"Guardrail G8 Evidenz",
     "q":"Was verlangt Guardrail G8 fuer jede Empfehlung des Agenten?",
     "kw":["guardrail g8","evidenz","g8 datenfeld","mindestens ein datenfeld"]},
    {"id": 97, "task":"ESK", "label":"Alle 8 Guardrails Uebersicht",
     "q":"Nenne und erklaere alle 8 Guardrails des Bayer Credit Analyst Agenten.",
     "kw":["alle guardrails","alle 8 guardrails","guardrail uebersicht","g1 bis g8"]},
    {"id": 98, "task":"ESK", "label":"Tier 2 Trigger",
     "q":"Unter welchen Bedingungen wird eine Anfrage automatisch an Tier 2 eskaliert?",
     "kw":["tier 2 trigger","tier 2 automatisch","eskalation tier 2","wann tier 2"]},
    {"id": 99, "task":"ESK", "label":"Tier 3 Credit Committee",
     "q":"Welche Faelle landen beim Credit Committee (Tier 3)?",
     "kw":["credit committee","tier 3 faelle","tier 3 committee","wann tier 3"]},
    {"id":100, "task":"ESK", "label":"Gesamtuebersicht Agent",
     "q":"Gib eine vollstaendige Uebersicht ueber alle Faehigkeiten des Bayer Credit Analyst Agenten.",
     "kw":["gesamtuebersicht agent","vollstaendige uebersicht","agent faehigkeiten","complete overview agent"]},
]
